version: "3.9"
name: "spa-prd"
services:
  api:
    build:
      args:
        MODE: production
    volumes:
      - ./api/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - ./api/.env.prd

  worker:
    build:
      args:
        MODE: production
    env_file:
      - ./api/.env.prd

  pgsql:
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  client:
    build:
      target: build-stage
      args:
        MODE: production
